name: Deploy test-cicd
on: [ push ]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{secrets.SSH_HOST}}
          username: ${{secrets.username}}
          password: ${{secrets.password}}
          script_stop: true
          script: |
            ls -al
            cd ../
            ls -al
            cd ~
            ls -al
#            cd root/resource/nginx
#            rm -rf test-cicd
#            git clone git@github.com:ZengWeiFeng993/test-cicd.git -b ${{ github.ref_name }}
#            cd test-cicd
#            npm i
#            npm run build


